### ISSUE TITLE
device detection

### ISSUE THREAD

**Issue by pidisaster** [kempniu/evmapy#2]
well i did manage to figure out how to come into root user but
but the problem is the custom keypad is not seen as device under root as it is under evtest
 i assembeld a custom .dtbo   "soc.keypad"
with the code 
/dts-v1/;
/plugin/;
/ {
	compatible = "brcm,bcm2835", "brcm,bcm2708", "brcm,bcm2709";
	
	fragment@0 {
		target-path = "/soc";
		__overlay__ {
			keypad: keypad {
				compatible = "gpio-keys";
				#address-cells = <1>;
				#size-cells = <0>;
				button@5 {
					label = "Test BTN0";
					linux,code = <103>;
					gpios = <&gpio 5 1>;
				};
				button@6 {
					label = "Test BTN1";
					linux,code = <105>;
					gpios = <&gpio 6 1>;
				};
				button@12 {
					label = "Test BTN2";
					linux,code = <108>;
					gpios = <&gpio 12 1>;
				};
				button@13 {
					label = "Test BTN3";
					linux,code = <106>;
					gpios = <&gpio 13 1>;
				};
				button@16 {
					label = "Test BTN4";
					linux,code = <0x104>;
					gpios = <&gpio 16 1>;
				};
				button@18 {
					label = "Test BTN5";
					linux,code = <0x105>;
					gpios = <&gpio 18 1>;
				};
			};
		};
	};
};
the idea is to press a gpio key ( 3 ) on my adafruit display and send out LEFTCTRL-LEFTarrow 
![afbeelding](https://user-images.githubusercontent.com/61390119/75283911-041fbb00-5814-11ea-9977-1c31299f091e.png)

**Comment by kempniu** [comment]
> the problem is the custom keypad is not seen as device under root as it is under evtest

What do you mean it is "not seen"?  I do not see an invocation of `evmapy --list-all` in the screenshot.  That would list the devices visible to evmapy, as shown in the [crash course](https://github.com/kempniu/evmapy#crash-course).

evmapy looks for configuration files in the `.evmapy` directory in the home directory *of the user it is running as*.  Thus, it will use a different configuration directory when you run it as `pi` (`/home/pi/.evmapy`) and a different one when you run it as `root` (`/root/.evmapy`).

The configuration file found in your `/root/.evmapy` directory appears to be broken, as indicated by evmapy output.  You likely need to move your configuration over from `/home/pi/.evmapy` to `/root/.evmapy` if you were previously running experiments as the `pi` user.

I am unable to help you with getting Device Trees right for your platform.

Given the description you provided, I have yet to see what evmapy is doing wrong here, so I will close this issue for the time being.  Feel free to reopen if you still believe something is broken in evmapy itself.
