### ISSUE TITLE
unable to set run as root in boot up

### ISSUE THREAD

**Issue by pidisaster** [kempniu/evmapy#3]
i have gotten it to run and simulate a keyboard combination LEFTCTRL_LEFT in this case 
https://www.youtube.com/watch?v=oTiOaK40zhc
but i have no idea how to make it run at bootup 
i made the desktop entry but it is not working 
tried lxsession autostart no joy there 
rc.local..... etc 
![afbeelding](https://user-images.githubusercontent.com/61390119/75633875-36ad2780-5c09-11ea-8738-f47047dc8d3c.png)
it does work as you can see
at the moment without inspiration :(

**Comment by kempniu** [comment]
Is the top-level [README.rst](https://github.com/kempniu/evmapy#how-do-i) file not good enough in terms of inspiration?  The "systemd service" part is relevant to your question, combined with a web search for setting up systemd services on your operating system.  Please do not make me paste a LMGTFY link.
