### ISSUE TITLE
probably installed wrong 

### ISSUE THREAD

**Issue by pidisaster** [kempniu/evmapy#4]
the is no evmapy in my /usr/bin/
probably why my evmapy.desktop does not work 

![afbeelding](https://user-images.githubusercontent.com/61390119/75699882-792a3f00-5cb1-11ea-8071-5c583673cace.png)
![afbeelding](https://user-images.githubusercontent.com/61390119/75699906-83e4d400-5cb1-11ea-9b00-0d9f64c6f2b1.png)
![afbeelding](https://user-images.githubusercontent.com/61390119/75699938-8f37ff80-5cb1-11ea-8fc2-fd981fe4b70a.png)
![afbeelding](https://user-images.githubusercontent.com/61390119/75699966-a24acf80-5cb1-11ea-958f-4d3d7ec9cc17.png)

**Comment by kempniu** [comment]
Did you run `python3 setup.py install` as described [in the `README`](https://github.com/kempniu/evmapy#installation)?  I assume it produced some output, maybe even errors?  I am unable to help you if you only show me the current state of your system without letting me know *how* your system reached that state.

If it works fine when run as `evmapy`, then running `which evmapy` will give you the absolute path to the binary.  You can put that into the systemd service file and it should work.
