### ISSUE TITLE
Reorder joystick buttons

### ISSUE THREAD

**Issue by mcmirande** [kempniu/evmapy#7]
Hi, thanks for your program!  I couldn't get what I need but it was a lot of fun to try it, hehe.

Basically I need to reorder the buttons of a Logitech Wheel for an old racing simulator I play.  I need, for example, the button13 (code 300) to be read as button1 (code 288).  
With evmapy I could achieve the button1 to be targeted as button13 and conversely when I test it with "evmapy --debug".  But when I test it with evtest (and oversteer, which is the program I use to set other options of the wheel), the button corresponding to "code 300" is always read as "code 300" instead of "code 288" as I need.  

In this example I would expect the button1 (Code 288 BTN_JOYSTICK) to execute Code 303 (BTN_DEAD), but it's still detected by evtest (when I press it on the wheel) as Code 288.

`{
    "actions": [
        {
            "trigger": "BTN_JOYSTICK",
            "type": "key",
            "target": "BTN_DEAD"
        },
...
        {
            "name": "BTN_DEAD",
            "code": 303
        },
{`

I don't know if modifying that is even possible with evmapy or not.  If it can't be done with evmapy, could you give me some clue about a possible solution to read about? 

Thanks a lot in advance, Marcos.

**Comment by kempniu** [comment]
Hi Marcos,

What you are trying to achieve should be possible with `evmapy`.  Two points that immediately come to mind:

 1. Do you have `"grab": true` set in your device's `evmapy` configuration file?  If not, then the default input event for each action will still be raised by the operating system.  If you are trying to swap two buttons with each other, not using `"grab": true` will result in *both* events being raised for each of the buttons.

 2. Are you aware that `evmapy` needs to be running in order for the configured processing rules to be in effect?  `evmapy` works by capturing input events and reacting to them "live".

**Comment by mcmirande** [comment]
Hi, thanks for your answer!

Putting `"grab": true` my wheel doesn't work at all in other programs... Thus, it's recognized only by evmapy, so I think I'm still doing something wrong.

Thanks again, cheers. Marcos.

**Comment by kempniu** [comment]
That is exactly what is supposed to happen with `"grab": true`: `evmapy` becomes the only recipient of the input events generated by the input device(s) it handles.  You cannot have it both ways: either `evmapy` has full control over a given device (`"grab": true`) or it does not (`"grab": false`).  In the latter case, other applications listening for input events (like your X.org server's input driver) will also receive events raised by your device(s) and process them.  You cannot tell `evmapy` to only grab a device for specific events.  What you can do is configure all buttons in your `evmapy` configuration file for the device, only swapping the two buttons you are interested in, and setting `"grab": true`.

**Comment by mcmirande** [comment]
Yes, I got all the configuration of the wheel with `evmay --configure /dev/input/event*` and modified the file generated according to my need, keeping all the remaining configuration unaltered.
Maybe I should use `"grab": true` only to test if `evmapy` is doing what I want, and after confirming that, put `"grab": false` to leave other programs use the device.  I'm not sure is already tried that, actually...

Thanks a lot and I'm sorry for the insistence.  Marcos.

**Comment by kempniu** [comment]
Yes, if you want to prevent the default events from being raised, you have to use `"grab": true`.  But you do not need to revert to `"grab": false` later on because when `evmapy` exits, it will stop affecting input event processing in any way.

Think of `evmapy` as a filter:

  - It only affects input event processing when it is running.
  - With `"grab": true`, it is installed in "exclusive" mode: events from the devices `evmapy` is configured for are only delivered to `evmapy`.
  - With `"grab": false`, it is installed in "parallel" mode: events from the devices `evmapy` is configured for are delivered both to `evmapy` and to other similar "filters" (like X.org input drivers).

I am going to close this issue for now.  Feel free to reopen it if you come to the conclusion that `evmapy` is not behaving as described above or in the documentation.
